create table if not exists public.analyses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  filename text not null,
  score double precision not null,
  matched_skills_count integer not null,
  missing_skills_count integer not null,
  analysis_json jsonb not null
);
